---
title: "566 Project Data Exploration"
author: "North Carpenter"
date: "2026-05-12"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(dplyr)
library(tidyr)
library(sf)
library(ggplot2)
```

# Importing Data

```{r}
# This block will import key data. It is imparative that you structure your
# files in the same way or this will not work. Set up this file in the 
# Y-crash-project folder somewhere on your computer and at the same level of the 
# project folder put the 566 project data folder.
#
# You should be able to import the files in 566 in this chunk only without issue.

# Importing Data

# Import any csv's here
accident2023 <- read.csv("../566 Project Data/FARS2023NationalCSV/accident.csv")
person2023 <- read.csv("../566 Project Data/FARS2023NationalCSV/PERSON.csv")
vehicle2023 <- read.csv("../566 Project Data/FARS2023NationalCSV/VEHICLE.csv")
drdistract2023 <- read.csv("../566 Project Data/FARS2023NationalCSV/distract.csv")
factor2023 <- read.csv("../566 Project Data/FARS2023NationalCSV/factor.csv")
nmCrash2023 <- read.csv("../566 Project Data/FARS2023NationalCSV/nmcrash.csv")

# Just Curios
drugs2023 <- read.csv("../566 Project Data/FARS2023NationalCSV/drugs.csv")
```

# Data Overiview

```{r}
looknon <- function(df)
{
  # Take a DF and returns a new df that counts na/"" in one column and 
  # "None"/"none" in another column. Also returns the number of unique values 
  # per column.
  
  df <- df |>
    mutate(across(everything(), as.character)) %>% #make everything char for ==
    pivot_longer(everything(), names_to = "column", values_to = "value") %>%
    group_by(column) %>% # set up groups
    summarise(
      num_missing = sum(is.na(value) | value == "", na.rm = TRUE),
      num_None = sum(value == "None" | value == "none", na.rm = TRUE),
      num_unique  = n_distinct(value)
    ) #summarize to these col
  return(df)
}
```

## Acidedent Summary
```{r}
looknon(accident2023)

vehicle2023 |>
  count(VPAVETYPNAME)

vehicle2023 |>
  count(VSURCONDNAME)
```

## Pedestrians and Injuries
```{r}
person2023 |>
  group_by(PER_TYPNAME, INJ_SEVNAME) |>
  summarise(n = n(), .groups = "drop") |>
  pivot_wider(
    names_from  = INJ_SEVNAME,
    values_from = n,
    values_fill = 0
  )
```

## Person Type
```{r}
person2023 |>
  count(PER_TYPNAME)

person2023 |>
  group_by(PER_TYPNAME, DRINKINGNAME) |>
  summarise(n = n(), .groups = "drop") |>
  pivot_wider(
    names_from  = DRINKINGNAME,
    values_from = n,
    values_fill = 0
  )
```


## Alcohol
```{r}
person2023 |>
  count(ALC_RESNAME)

person2023 |>
  count(DRINKINGNAME)

person2023 |>
  group_by(PER_TYPNAME, DRINKINGNAME) |>
  summarise(n = n(), .groups = "drop") |>
  pivot_wider(
    names_from  = DRINKINGNAME,
    values_from = n,
    values_fill = 0
  )
```

## Drugs
```{r}
drugtype <- drugs2023 |> 
  group_by(DRUGRESNAME) |> 
  summarise(n = n()) |> 
  mutate(percent = n / sum(n))
drugtype

drugs2023 |>
  count(DRUGRESNAME)
```

# Pretty Pictures
```{r}
accident2023noLat <- accident2023 |>
  filter(STATENAME != "Alaska",
         LATITUDE > 24, LATITUDE < 72,
         LONGITUD > -180, LONGITUD < -65)


my_sf <- st_as_sf(accident2023noLat, coords = c('LONGITUD', 'LATITUDE'))

my_sf <- st_set_crs(my_sf, 4326)

#Plot it:

ggplot(my_sf) + 
  geom_sf(aes(color = STATENAME), size = 0.01) +
  theme(legend.position = "none")

```

```{r}
accident2023seattle <- accident2023 |>
  filter(STATENAME == "Connecticut",
         LATITUDE > 24, LATITUDE < 72,
         LONGITUD > -180, LONGITUD < -65)

axSeattleMap <- st_as_sf(accident2023seattle, coords = c('LONGITUD', 'LATITUDE'))

axSeattleMap <- st_set_crs(axSeattleMap, 4326)

#Plot it:

ggplot(axSeattleMap) + 
  geom_sf(aes(color = FATALS), size = 1)

```

# Cleaning
## Setting Up Variables to Keep
```{r}
merging_Vars <- c("ST_CASE", "VEH_NO", "PER_NO")
accident_keep <- c("VE_FORMS", "MONTH", "DAY", "YEAR", "HOUR", "MINUTE", "DAY_WEEK", "ROUTE", "RUR_URB", "RELJCT1", "LGT_COND", "WEATHER")
vehicle_keep <- c("TRAV_SP", "DR_DRINK", "PREV_ACC", "VSPD_LIM", "VPAVETYP", "VSURCOND", "P_CRASH1")
person_keep <- c("AGE", "SEX", "PER_TYP", "INJ_SEV", "DRUGS", "DEATH_MO", "DEATH_DA", "DEATH_YR", "DEATH_TM", "DEATH_HR", "DEATH_MN", "LAG_HRS", "LAG_MINS") #Record Sex of Driver Only, fix type, fix type, complex death after indicator
fact_keep <- c("VEHICLECC")
dist_keep <- c("DRDISTRACT")
NMCC_keep <- c("NMCC")
```

## Triming Files
```{r}
data_list <- list(accident2023, vehicle2023, person2023, factor2023, drdistract2023, nmCrash2023)
var_list <- list(accident_keep, vehicle_keep, person_keep, fact_keep, dist_keep, NMCC_keep)

data_list <- Map(function(df, vars){
  df %>% select(any_of(c(merging_Vars, vars)))
}, data_list, var_list)
```

## Check Worked
```{r}
lapply(data_list, head)
```

## Joining
```{r}
crashes2023 <- left_join(data_list[[3]], data_list[[1]], by = join_by(ST_CASE))

data_list[[6]] |>
  filter(ST_CASE == 10014, PER_NO == 1)

person2023 |>
  filter(ST_CASE == 10014)

vehicle2023 |> 
  count(ST_CASE) |> 
  arrange(desc(n))

crashes2023 <- left_join(crashes2023, data_list[[6]], by = join_by(ST_CASE, PER_NO))
```

